{{- if and .Values.rbac.create .Values.controller.leaderElect }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "craft-ai-platform.fullname" . }}-leader-election
  namespace: {{ include "craft-ai-platform.namespace" . }}
  labels:
    {{- include "craft-ai-platform.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "craft-ai-platform.fullname" . }}-leader-election
  namespace: {{ include "craft-ai-platform.namespace" . }}
  labels:
    {{- include "craft-ai-platform.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "craft-ai-platform.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "craft-ai-platform.serviceAccountName" . }}
    namespace: {{ include "craft-ai-platform.namespace" . }}
{{- end }}
