{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "craft-ai-platform.fullname" . }}
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ include "craft-ai-platform.namespace" . }}
  {{- end }}
  labels:
    {{- include "craft-ai-platform.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - {{ include "craft-ai-platform.namespace" . }}
  selector:
    matchLabels:
      {{- include "craft-ai-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
{{- end }}
